### ISSUE TITLE
Source Interface binding failed due to incorrect length value

### ISSUE THREAD

**Issue by swapniil** [michalgarcarz/radiustest#1]
Radius client is unable to bind to source interface. This is required to capture response packets coming towards the utility.
![image](https://user-images.githubusercontent.com/12267463/201360499-ddc5a6b3-8b06-46c2-8bd6-4c7ee4164925.png)

```python2 radius-accttest.py  -dp 1813 -t 4 -s test -u cisco -p cisco -an 1.1.1.1 -d 172.16.0.61 -sp 666 -n 1 -as framed -ap ethernet -ac 11:22:33:44:55:66 -ai 55:55:55:55:55:55 
Starting sniffing daemon
Choosen eth interface for sniffing
Sniffing traffic from udp and src 172.16.0.61 and port 1813
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "radius-accttest.py", line 144, in threaded_sniff_target
    sniff(iface = m_iface, timeout = timeout, filter = "udp and src {0} and port {1}".format(host,port), prn = lambda x : q.put(x))
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 19] No such device

**Comment by swapniil** [comment]
Patch File:

```diff --git a/radius-accttest.py b/radius-accttest.py
index a54d4e4..9864aa1 100644
--- a/radius-accttest.py
+++ b/radius-accttest.py
@@ -133,7 +133,7 @@ def threaded_sniff_target(q,host,timeout,port):
     p = subprocess.Popen(["ip", "route", "get", host], stdout=subprocess.PIPE)
     x = str(p.stdout.read())
     y = x[x.find("dev"):x.find("src")]
-    m_iface = y[y.find(" ")+1:len(y)-2]
+    m_iface = y[y.find(" ")+1:len(y)-1]
 
     print "Choosen %s interface for sniffing" % m_iface
     fff = "udp and src {0} and port {1}".format(host,port)
diff --git a/radiusattr.pyc b/radiusattr.pyc
deleted file mode 100644
index 2787609..0000000
Binary files a/radiusattr.pyc and /dev/null differ
diff --git a/radiusext.pyc b/radiusext.pyc
deleted file mode 100644
index cc59d1f..0000000
Binary files a/radiusext.pyc and /dev/null differ
diff --git a/radiustest.py b/radiustest.py
index 16286f8..5d1dd11 100644
--- a/radiustest.py
+++ b/radiustest.py
@@ -128,7 +128,7 @@ def threaded_sniff_target(q,host,timeout,port):
     p = subprocess.Popen(["ip", "route", "get", host], stdout=subprocess.PIPE)
     x = str(p.stdout.read())
     y = x[x.find("dev"):x.find("src")]
-    m_iface = y[y.find(" ")+1:len(y)-2]
+    m_iface = y[y.find(" ")+1:len(y)-1]
 
     print "Choosen %s interface for sniffing" % m_iface
     fff = "udp and src {0} and port {1}".format(host,port)
